/******************************************************************************
* File Name:   N25Q03.h
*
* Description: This is the source code for the XMC MCU: SPI QSPI Flash
*              Example for ModusToolbox. This file includes the function
*              definitions for interfacing the on-board N25Q03 memory chip
*              in the XMC4700 Relax kit V1 and XMC4800 Relax EtherCAT kit V1,
*              the on-board S25FL032P0XMFI01 memory chip in the XMC4500 Relax
*              kit V1 or the on-board SST26VF032BT-104I/SM memory chip
*              in the XMC4400 Platform2Go kit.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2022, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include <stdint.h>
#include <stdbool.h>

/*******************************************************************************
 * Function Prototypes
 *******************************************************************************/
uint16_t memory_status_read(void);
void memory_sector_erase(uint32_t address);
void memory_write_enable(void);
void memory_quad_read_page(uint32_t address, uint8_t *p_spi_receive_data);
void memory_quad_write_page(uint32_t address, uint8_t *p_spi_send_data);
void memory_read_page(uint32_t address, uint8_t *p_spi_receive_data);
void memory_program_page( uint32_t address, uint8_t *p_spi_send_data);
void memory_write_protection(void);

/* [] END OF FILE */
