/******************************************************************************
* File Name:   N25Q03.h
*
* Description: This is the source code for the XMC MCU: SPI QSPI Flash
*              Example for ModusToolbox. This file includes the function
*              declarations for interfacing the on-board N25Q03 memory
*              chip in the XMC4700 Relax kit V1.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include <stdint.h>
#include <stdbool.h>

/*******************************************************************************
 * Function Prototypes
 *******************************************************************************/
void N25Q03_ReadPage(uint32_t address, uint8_t *pSPIReceiveData);
uint16_t N25Q03_StatusRead(void);
void N25Q03_ProgramPage(uint32_t address, uint8_t *pSPISendData);
void N25Q03_SectorErase(uint32_t address);
void N25Q03_WriteEnable();
void N25Q03_QuadWritePage(uint32_t address, uint8_t *pSPISendData);
void N25Q03_QuadReadPage(uint32_t address, uint8_t *pSPIReceiveData);

/* [] END OF FILE */
